matrix:
  include:
    - language: sass
      before_install:
        - gem install sass
      script:
        - test/ruby-sass/ruby-sass.sh
    - language: node_js
      node_js:
        - node
      before_script:
        - npm install sass
      script:
        - node test/dart-sass/dart-sass.js
    - language: node_js
      node_js:
        - node
      script:
        - node test/sass/sass.js
